export const highscoreList = [
  {
    createdAt: "2022-11-26T02:45:24Z",
    id: 10534,
    user: {
      bio: "I am just improving my typing skills.",
      country: "United States",
      id: 10534,
      insertedAt: "2022-11-26T02:45:24Z",
      isAdmin: false,
      username: "UdekaRana",
    },
    wpm: 289.27,
  },
  {
    createdAt: "2021-07-26T23:56:18Z",
    id: 3705,
    user: {
      bio: "Information\nLayout: QWERTY\nKeyboard: Laptop\nI use 10 fingers.\nI started typing actively on April 2021.\n\nProfiles\nTypeRacer: typos_z (Rank #3 TB)\nNitroType: typos_z\nMonkeyType: Algorox (Top 0.01%)\nKeymash: Alternator#5442\nYouTube: Algorox\nDiscord: Alternator#1457\nROBLOX: TisfatDude0704\n\nRecords\n07/25/2021 - 203 wpm\n07/26/2021 - 226 wpm\n07/30/2021 - 227 wpm\n07/30/2021 - 231 wpm\n07/31/2021 - 249 wpm\n09/17/2021 - 250.43 wpm\n10/04/2021 - 252.77 wpm\n10/13/2021 - 255 wpm\n11/26/2021 - 255.27 wpm\n01/25/2022 - 265 wpm\n02/11/2022 - 274.29 wpm\n\nLiveplay\nhttps://www.youtube.com/watch?v=q3y0-oo9QdQ",
      country: "Canada",
      id: 3705,
      insertedAt: "2021-07-26T23:56:18Z",
      isAdmin: false,
      username: "typos_z",
    },
    wpm: 274.29,
  },
  {
    createdAt: "2024-12-26T15:44:33Z",
    id: 72465,
    user: {
      bio: "🌟 Hello, I'm a Fat Monkey! 🐒🍌\n✨🍌 Banana-Lover & Typing Legend! 🍌✨\n\n🐾 About Me:\nI’m all about smashing leaderboards 🏆, devouring bananas 🍌, and typing like a beast! 🖋️💨 Swinging through letters like vines 🌴, I make keystrokes my superpower ⚡.\n\n🍌 Why I Type:\nTyping is my jungle, and I’m here to inspire monkeys 🐵 & humans alike to Keep Calm & Type On! 💻🙈\n\n",
      country: "United Kingdom",
      id: 72465,
      insertedAt: "2024-12-26T15:44:33Z",
      isAdmin: false,
      username: "Fat Monkey",
    },
    wpm: 272.62,
  },
  {
    createdAt: "2021-08-05T13:00:40Z",
    id: 3863,
    user: {
      bio: "El goog la googa le agoog La el La Le googie googa googies.",
      country: null,
      id: 3863,
      insertedAt: "2021-08-05T13:00:40Z",
      isAdmin: false,
      username: "Googas",
    },
    wpm: 230.4,
  },
  {
    createdAt: "2022-08-01T10:09:55Z",
    id: 9316,
    user: {
      bio: null,
      country: null,
      id: 9316,
      insertedAt: "2022-08-01T10:09:55Z",
      isAdmin: false,
      username: "TheGame",
    },
    wpm: 216.3,
  },
  {
    createdAt: "2024-05-01T21:27:02Z",
    id: 17140,
    user: {
      bio: "Hey there, I'm Tahoonga and my main goal is to score an average of 145 WPM on all tests, no matter how tricky they get. My personal best is 216 WPM. i use laptop for almost all my records on here.",
      country: "United States",
      id: 17140,
      insertedAt: "2024-05-01T21:27:02Z",
      isAdmin: false,
      username: "Tahoonga",
    },
    wpm: 216,
  },
  {
    createdAt: "2022-02-28T00:20:01Z",
    id: 7228,
    user: {
      bio: "CHECKPOINTS:\n1000 games - 9.26.24\nAvg: 138.25WPM / 95.62% / 12.93 errors\n\n2000 games - TBD",
      country: "United States",
      id: 7228,
      insertedAt: "2022-02-28T00:20:01Z",
      isAdmin: false,
      username: "Nobilissima",
    },
    wpm: 214.88,
  },
  {
    createdAt: "2024-08-09T23:34:15Z",
    id: 28772,
    user: {
      bio: null,
      country: null,
      id: 28772,
      insertedAt: "2024-08-09T23:34:15Z",
      isAdmin: false,
      username: "joseph",
    },
    wpm: 210,
  },
  {
    createdAt: "2023-09-19T20:50:34Z",
    id: 13986,
    user: {
      bio: "taking a break for keymash.",
      country: "United States",
      id: 13986,
      insertedAt: "2023-09-19T20:50:34Z",
      isAdmin: false,
      username: "Lego",
    },
    wpm: 208.42,
  },
  {
    createdAt: "2022-03-25T00:58:47Z",
    id: 7623,
    user: {
      bio: null,
      country: "United States",
      id: 7623,
      insertedAt: "2022-03-25T00:58:47Z",
      isAdmin: false,
      username: "dannysaur",
    },
    wpm: 205.71,
  },
  {
    createdAt: "2023-10-21T07:19:04Z",
    id: 14325,
    user: {
      bio: null,
      country: null,
      id: 14325,
      insertedAt: "2023-10-21T07:19:04Z",
      isAdmin: false,
      username: "learner",
    },
    wpm: 196.57,
  },
  {
    createdAt: "2024-11-02T20:53:03Z",
    id: 55306,
    user: {
      bio: "adsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsaadsfasdfadsfasdfdsa",
      country: "India",
      id: 55306,
      insertedAt: "2024-11-02T20:53:03Z",
      isAdmin: false,
      username: "fuckyoumfs",
    },
    wpm: 188.57,
  },
  {
    createdAt: "2021-06-30T04:26:28Z",
    id: 3392,
    user: {
      bio: "https://keyma.sh/profile/Yogit-3317\n160wpm+ on monkeytype",
      country: null,
      id: 3392,
      insertedAt: "2021-06-30T04:26:28Z",
      isAdmin: false,
      username: "yogit_typer",
    },
    wpm: 186.46,
  },
  {
    createdAt: "2023-04-16T04:38:51Z",
    id: 12404,
    user: {
      bio: null,
      country: "Malaysia",
      id: 12404,
      insertedAt: "2023-04-16T04:38:51Z",
      isAdmin: false,
      username: "TheBird",
    },
    wpm: 185.45,
  },
  {
    createdAt: "2024-11-03T05:05:41Z",
    id: 55568,
    user: {
      bio: null,
      country: null,
      id: 55568,
      insertedAt: "2024-11-03T05:05:41Z",
      isAdmin: false,
      username: "SecretAnimals",
    },
    wpm: 181.87,
  },
  {
    createdAt: "2021-05-23T11:23:02Z",
    id: 2822,
    user: {
      bio: "typeracer: juij\n",
      country: null,
      id: 2822,
      insertedAt: "2021-05-23T11:23:02Z",
      isAdmin: false,
      username: "Jimmy",
    },
    wpm: 178,
  },
  {
    createdAt: "2022-10-16T03:28:06Z",
    id: 10033,
    user: {
      bio: null,
      country: null,
      id: 10033,
      insertedAt: "2022-10-16T03:28:06Z",
      isAdmin: false,
      username: "themagicianhere",
    },
    wpm: 178,
  },
  {
    createdAt: "2023-05-19T17:33:34Z",
    id: 12761,
    user: {
      bio: "\nmy typeracer profile : https://data.typeracer.com/pit/profile?user=zak389\n\ndiscord : zakswagg\n\nsome typing videos i made : https://www.youtube.com/watch?v=l4dQfekz2-E&list=PLrCKQ-Mz1n9NwaFZXIriEgayNown-E9Zg\n\nrarely using 10ff, keymash and mt tho",
      country: "Algeria",
      id: 12761,
      insertedAt: "2023-05-19T17:33:34Z",
      isAdmin: false,
      username: "ZakSwagG",
    },
    wpm: 177.81,
  },
  {
    createdAt: "2021-08-29T17:58:57Z",
    id: 4211,
    user: {
      bio: "I just type with one finger..",
      country: "India",
      id: 4211,
      insertedAt: "2021-08-29T17:58:57Z",
      isAdmin: false,
      username: "zigo",
    },
    wpm: 177.31,
  },
  {
    createdAt: "2022-09-09T06:50:07Z",
    id: 9678,
    user: {
      bio: "too fast and slightly furious",
      country: null,
      id: 9678,
      insertedAt: "2022-09-09T06:50:07Z",
      isAdmin: false,
      username: "KORDHELL",
    },
    wpm: 175.29,
  },
  {
    createdAt: "2021-12-31T06:02:54Z",
    id: 6289,
    user: {
      bio: "Reached my target, now trying to be consistent\n",
      country: "India",
      id: 6289,
      insertedAt: "2021-12-31T06:02:54Z",
      isAdmin: false,
      username: "Batman",
    },
    wpm: 174.74,
  },
  {
    createdAt: "2022-02-26T05:05:41Z",
    id: 7210,
    user: {
      bio: null,
      country: "Canada",
      id: 7210,
      insertedAt: "2022-02-26T05:05:41Z",
      isAdmin: false,
      username: "injust",
    },
    wpm: 173.96,
  },
  {
    createdAt: "2023-01-13T00:37:42Z",
    id: 11184,
    user: {
      bio: "thock thock thock",
      country: "United States",
      id: 11184,
      insertedAt: "2023-01-13T00:37:42Z",
      isAdmin: false,
      username: "Lazlo",
    },
    wpm: 171.15,
  },
  {
    createdAt: "2022-02-03T11:30:39Z",
    id: 6733,
    user: {
      bio: "🤨",
      country: "Nepal",
      id: 6733,
      insertedAt: "2022-02-03T11:30:39Z",
      isAdmin: false,
      username: "bijay",
    },
    wpm: 169.09,
  },
  {
    createdAt: "2023-09-26T00:24:12Z",
    id: 14059,
    user: {
      bio: "surprised no one took this username before me",
      country: null,
      id: 14059,
      insertedAt: "2023-09-26T00:24:12Z",
      isAdmin: false,
      username: "deeznuts",
    },
    wpm: 168,
  },
];

export const postList = [
  {
    body: "is the creator of this game dead or what cuz i want new updates\nany ogs please tell me\nor did he take a break and work on new games?\nhelp, im so confused.",
    commentCount: 9,
    createdAt: "2025-02-16T06:24:55Z",
    id: 2234,
    title: "no updates??",
    updatedAt: "2025-02-21T14:58:05Z",
    user: {
      id: 86365,
      insertedAt: "2025-02-14T12:36:43Z",
      isAdmin: false,
      username: "hxnnahh",
    },
  },
  {
    body: 'saying of the day, "Its free to be kind"\n\nHope everyone is having a good Monday! I hope yall are doing well and had a good weekend. :D',
    commentCount: 0,
    createdAt: "2025-02-17T14:52:40Z",
    id: 2267,
    title: "Monday❤️",
    updatedAt: "2025-02-17T14:52:40Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "Saying of the day, \"You cannot do long lasting work with motivation, instead discipline.\"\n\nHope everyone's doing AMAZINGGGGGGG hope y'all are doing well today, today is my Friday! so I wont be back until Monday :) finally getting out of alternative school and going into pace!",
    commentCount: 5,
    createdAt: "2025-02-13T15:07:18Z",
    id: 2201,
    title: "Thursday ❤️",
    updatedAt: "2025-02-17T14:50:28Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "Does anyone talk or type on this website anymore? I swear I run into people and no one talks and when I get in their match they just leave like why? I remember about a year ago I meet a friend named DanielP me and him we always chatted, but now no one talks or types. Whatever maybe it's just me. Well, Happy typing Everyone and have a nice day! :)",
    commentCount: 7,
    createdAt: "2025-02-04T23:55:12Z",
    id: 1970,
    title: "Anyone?",
    updatedAt: "2025-02-16T17:34:30Z",
    user: {
      id: 4615,
      insertedAt: "2021-09-24T16:30:02Z",
      isAdmin: false,
      username: "Boom",
    },
  },
  {
    body: 'saying of the day 2/12/24 "Whats meant for you will always be meant for you" \nRemember that love is patient love is kind, and love is like a diamond. it takes a long time to create something that beautiful. Hope everyone is having a wonderful morning and have a good rest of yalls day, happy typing friends! :) ',
    commentCount: 0,
    createdAt: "2025-02-12T15:53:56Z",
    id: 2168,
    title: "Wednesday ❤️",
    updatedAt: "2025-02-12T15:53:56Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "saying of the day 2/11/25 \"Always remember to be kind to yourself, our hardest critique is ourselves.\" ❤️ \n\nHIII GOOOODDDDMORNINNGGGGG melly here once again. I think I'm gonna make this a daily thing on school days maybe during the weekend too even when I'm out of school. I hope to whoever is reading this that y'all have an amazing Tuesday, and remember that when people are mean to you are rude it's because they have problems with themselves or at home that they can't or refuse to change. :)) if you're interested in being friends ILL BE ON MOST OF THE DAY (times that are listed on my profile! if you're interested in being friends outside the game my discord will be also listed into my bio as well :) !!! GOOD LUCK and have FUN TYPING!",
    commentCount: 0,
    createdAt: "2025-02-11T14:50:11Z",
    id: 2135,
    title: "Tuesday❤️ ",
    updatedAt: "2025-02-11T14:50:11Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "saying of the day 2/10/25 😊\nTo whoever reads this. You ARE LOVED, I CARE about YOU, and never forget YOU MATTER.\n\nAnother school day for me, so another day to waste most of my time of this game which I LOVEEE. I've always loved typing so getting to go against people is pretty fun. I type weird tho, with my index finger on my left and my right my index and my middle finger, its just something I've always been accustom to. IF you're going against me, please say hi!!! :)))) \n\n",
    commentCount: 2,
    createdAt: "2025-02-10T14:34:53Z",
    id: 2102,
    title: "Monday ❤️",
    updatedAt: "2025-02-11T14:43:38Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "HEYYY just recently found this website. I don't think we can create like actual friends on here BUTTTTT I mean if anyone wants to chat, I'll be having this post in another tab Im low-key only gonna be playing this during school days which is mon-thurs 8:20- 4:20 because my PC at home is unfortunately broken. so if you wanna be friends outside of here comment your discord or something below and if ur not in school and ur just here I'll drop mine for you :))) HELLOOOO EVERYYYYONEEEEEEE",
    commentCount: 0,
    createdAt: "2025-02-06T16:58:31Z",
    id: 2036,
    title: "New friends??",
    updatedAt: "2025-02-06T16:58:31Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "I would like to be a version of this game in spanish. I think this game is amazing but is really difficult for me because im hispanic.",
    commentCount: 0,
    createdAt: "2025-02-05T21:45:19Z",
    id: 2003,
    title: "Different Languages Please!",
    updatedAt: "2025-02-05T21:45:19Z",
    user: {
      id: 83495,
      insertedAt: "2025-02-04T15:40:20Z",
      isAdmin: false,
      username: "aitorpetriz",
    },
  },
  {
    body: " please let me know how to redeem money and procedures",
    commentCount: 0,
    createdAt: "2025-01-28T04:52:47Z",
    id: 1937,
    title: "I'm a new player",
    updatedAt: "2025-01-28T04:52:47Z",
    user: {
      id: 80516,
      insertedAt: "2025-01-28T04:11:26Z",
      isAdmin: false,
      username: "Moon",
    },
  },
];

export const userData = {
  age: null,
  averageAccuracy: 91.42,
  averageErrors: 24.14,
  averageWpm: 58.74,
  bio: null,
  country: null,
  gender: null,
  id: 85573,
  insertedAt: "2025-02-11T11:42:41Z",
  isAdmin: false,
  matchCount: 36,
  posts: [],
  recentAverageAccuracy: 91.84,
  recentAverageErrors: 23.2,
  recentAverageWpm: 60.78,
  topWpm: 74.73,
  totalWins: 24,
  username: "vedant",
};

export const recordList = [
  {
    accuracy: 96,
    created_at: "2025-02-19T03:57:37Z",
    difficulty: "easy",
    id: 3181334,
    nickname: "vedant",
    snippetTitle: "The Godfather",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 74.73,
  },
  {
    accuracy: 99,
    created_at: "2025-02-22T06:01:52Z",
    difficulty: "easy",
    id: 3195556,
    nickname: "vedant",
    snippetTitle: "Josie and the Pussycats",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 74.38,
  },
  {
    accuracy: 94,
    created_at: "2025-02-12T12:09:04Z",
    difficulty: "medium",
    id: 3153202,
    nickname: "vedant",
    snippetTitle: "Don Quixote",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 71.72,
  },
  {
    accuracy: 93,
    created_at: "2025-02-23T05:28:15Z",
    difficulty: "easy",
    id: 3198055,
    nickname: "vedant",
    snippetTitle: "The Stories of Anton Chekhov",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 70.62,
  },
  {
    accuracy: 95,
    created_at: "2025-02-11T17:00:01Z",
    difficulty: "easy",
    id: 3149173,
    nickname: "vedant",
    snippetTitle: "What Are People For?",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 69.96,
  },
  {
    accuracy: 93,
    created_at: "2025-02-23T05:24:01Z",
    difficulty: "easy",
    id: 3198044,
    nickname: "vedant",
    snippetTitle: "Diary of a Wimpy Kid: The Getaway",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 67.45,
  },
  {
    accuracy: 95,
    created_at: "2025-02-22T06:00:55Z",
    difficulty: "medium",
    id: 3195555,
    nickname: "vedant",
    snippetTitle: "Burn Notice",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 66.41,
  },
  {
    accuracy: 93,
    created_at: "2025-02-23T05:25:17Z",
    difficulty: "medium",
    id: 3198048,
    nickname: "vedant",
    snippetTitle: "Faith of My Fathers",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 66.33,
  },
  {
    accuracy: 96,
    created_at: "2025-02-23T05:26:33Z",
    difficulty: "medium",
    id: 3198051,
    nickname: "vedant",
    snippetTitle: "The Catcher in the Rye",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 65.74,
  },
  {
    accuracy: 96,
    created_at: "2025-02-23T05:27:32Z",
    difficulty: "easy",
    id: 3198053,
    nickname: "vedant",
    snippetTitle: "Kono Subarashii Sekai ni Shukufuku wo!",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 63.57,
  },
];

export const matchHistoryList = [
  {
    accuracy: 93,
    created_at: "2025-02-23T05:28:15Z",
    difficulty: "easy",
    id: 3198055,
    nickname: "vedant",
    snippetTitle: "The Stories of Anton Chekhov",
    wpm: 70.62,
  },
  {
    accuracy: 96,
    created_at: "2025-02-23T05:27:32Z",
    difficulty: "easy",
    id: 3198053,
    nickname: "vedant",
    snippetTitle: "Kono Subarashii Sekai ni Shukufuku wo!",
    wpm: 63.57,
  },
  {
    accuracy: 96,
    created_at: "2025-02-23T05:26:33Z",
    difficulty: "medium",
    id: 3198051,
    nickname: "vedant",
    snippetTitle: "The Catcher in the Rye",
    wpm: 65.74,
  },
  {
    accuracy: 93,
    created_at: "2025-02-23T05:25:17Z",
    difficulty: "medium",
    id: 3198048,
    nickname: "vedant",
    snippetTitle: "Faith of My Fathers",
    wpm: 66.33,
  },
  {
    accuracy: 93,
    created_at: "2025-02-23T05:24:01Z",
    difficulty: "easy",
    id: 3198044,
    nickname: "vedant",
    snippetTitle: "Diary of a Wimpy Kid: The Getaway",
    wpm: 67.45,
  },
  {
    accuracy: 85,
    created_at: "2025-02-22T12:41:39Z",
    difficulty: "medium",
    id: 3196459,
    nickname: "vedant",
    snippetTitle: "The Simpsons",
    wpm: 44.64,
  },
  {
    accuracy: 99,
    created_at: "2025-02-22T06:01:52Z",
    difficulty: "easy",
    id: 3195556,
    nickname: "vedant",
    snippetTitle: "Josie and the Pussycats",
    wpm: 74.38,
  },
  {
    accuracy: 95,
    created_at: "2025-02-22T06:00:55Z",
    difficulty: "medium",
    id: 3195555,
    nickname: "vedant",
    snippetTitle: "Burn Notice",
    wpm: 66.41,
  },
  {
    accuracy: 95,
    created_at: "2025-02-22T05:59:37Z",
    difficulty: "medium",
    id: 3195553,
    nickname: "vedant",
    snippetTitle: "Jimi Hendrix",
    wpm: 62.24,
  },
  {
    accuracy: 95,
    created_at: "2025-02-22T05:57:45Z",
    difficulty: "hard",
    id: 3195552,
    nickname: "vedant",
    snippetTitle: "Star Trek: The Next Generation",
    wpm: 57.91,
  },
  {
    accuracy: 94,
    created_at: "2025-02-19T04:01:09Z",
    difficulty: "hard",
    id: 3181336,
    nickname: "vedant",
    snippetTitle: "Taken",
    wpm: 58.53,
  },
  {
    accuracy: 83,
    created_at: "2025-02-19T03:59:13Z",
    difficulty: "medium",
    id: 3181335,
    nickname: "vedant",
    snippetTitle: "The Power of Now",
    wpm: 50.18,
  },
  {
    accuracy: 96,
    created_at: "2025-02-19T03:57:37Z",
    difficulty: "easy",
    id: 3181334,
    nickname: "vedant",
    snippetTitle: "The Godfather",
    wpm: 74.73,
  },
  {
    accuracy: 85,
    created_at: "2025-02-14T03:42:33Z",
    difficulty: "easy",
    id: 3161444,
    nickname: "vedant",
    snippetTitle: "The Catcher in the Rye",
    wpm: 61.01,
  },
  {
    accuracy: 80,
    created_at: "2025-02-14T03:41:54Z",
    difficulty: "easy",
    id: 3161438,
    nickname: "vedant",
    snippetTitle: "The Iliad",
    wpm: 45.92,
  },
  {
    accuracy: 85,
    created_at: "2025-02-14T03:41:03Z",
    difficulty: "easy",
    id: 3161431,
    nickname: "vedant",
    snippetTitle: "Camber of Culdi",
    wpm: 52.16,
  },
  {
    accuracy: 87,
    created_at: "2025-02-14T03:40:03Z",
    difficulty: "medium",
    id: 3161425,
    nickname: "vedant",
    snippetTitle: "Yoda",
    wpm: 50.07,
  },
  {
    accuracy: 93,
    created_at: "2025-02-12T12:12:51Z",
    difficulty: "hard",
    id: 3153217,
    nickname: "vedant",
    snippetTitle: "Can't Hurt Me: Master Your Mind and Defy the Odds",
    wpm: 63.48,
  },
  {
    accuracy: 92,
    created_at: "2025-02-12T12:10:41Z",
    difficulty: "hard",
    id: 3153209,
    nickname: "vedant",
    snippetTitle: "The Recruit",
    wpm: 60.16,
  },
  {
    accuracy: 94,
    created_at: "2025-02-12T12:09:04Z",
    difficulty: "medium",
    id: 3153202,
    nickname: "vedant",
    snippetTitle: "Don Quixote",
    wpm: 71.72,
  },
  {
    accuracy: 94,
    created_at: "2025-02-12T04:42:31Z",
    difficulty: "hard",
    id: 3151818,
    nickname: "vedant",
    snippetTitle: "The Great Gatsby",
    wpm: 61.85,
  },
  {
    accuracy: 91,
    created_at: "2025-02-12T04:40:54Z",
    difficulty: "medium",
    id: 3151809,
    nickname: "vedant",
    snippetTitle: "Mrs. Robinson",
    wpm: 54.86,
  },
  {
    accuracy: 93,
    created_at: "2025-02-12T04:39:54Z",
    difficulty: "medium",
    id: 3151804,
    nickname: "vedant",
    snippetTitle: "Parks and Recreation",
    wpm: 50.47,
  },
  {
    accuracy: 95,
    created_at: "2025-02-11T17:00:01Z",
    difficulty: "easy",
    id: 3149173,
    nickname: "vedant",
    snippetTitle: "What Are People For?",
    wpm: 69.96,
  },
  {
    accuracy: 94,
    created_at: "2025-02-11T16:59:26Z",
    difficulty: "easy",
    id: 3149169,
    nickname: "vedant",
    snippetTitle: "The Count of Monte Cristo",
    wpm: 55.05,
  },
];

export const homeRecentMatches = [
  {
    created_at: "2025-02-26T01:48:04Z",
    id: 3208344,
    nickname: "graceful_Qu55",
    user: null,
    wpm: 32.57,
  },
  {
    created_at: "2025-02-26T01:47:58Z",
    id: 3208343,
    nickname: "gerly",
    user: null,
    wpm: 35.69,
  },
  {
    created_at: "2025-02-26T01:47:30Z",
    id: 3208342,
    nickname: "hmmmm",
    user: null,
    wpm: 38.87,
  },
  {
    created_at: "2025-02-26T01:47:16Z",
    id: 3208341,
    nickname: "bat90",
    user: null,
    wpm: 35.77,
  },
  {
    created_at: "2025-02-26T01:46:28Z",
    id: 3208340,
    nickname: "Anna",
    user: null,
    wpm: 35.38,
  },
  {
    created_at: "2025-02-26T01:46:12Z",
    id: 3208339,
    nickname: "Cabybara",
    user: null,
    wpm: 23.85,
  },
  {
    created_at: "2025-02-26T01:46:12Z",
    id: 3208338,
    nickname: "brain",
    user: null,
    wpm: 23.89,
  },
  {
    created_at: "2025-02-26T01:45:45Z",
    id: 3208337,
    nickname: "burne_mvzcyros",
    user: null,
    wpm: 26.53,
  },
  {
    created_at: "2025-02-26T01:45:42Z",
    id: 3208336,
    nickname: "ramen",
    user: null,
    wpm: 26.86,
  },
  {
    created_at: "2025-02-26T01:45:17Z",
    id: 3208335,
    nickname: "Mary :D",
    user: null,
    wpm: 29.99,
  },
  {
    created_at: "2025-02-26T01:44:19Z",
    id: 3208334,
    nickname: "Anna",
    user: null,
    wpm: 44.33,
  },
  {
    created_at: "2025-02-26T01:43:54Z",
    id: 3208333,
    nickname: "vedant",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 57.13,
  },
  {
    created_at: "2025-02-26T01:43:34Z",
    id: 3208332,
    nickname: "hmmmm",
    user: null,
    wpm: 46.67,
  },
  {
    created_at: "2025-02-26T01:42:46Z",
    id: 3208331,
    nickname: "bound90",
    user: null,
    wpm: 34.75,
  },
  {
    created_at: "2025-02-26T01:41:54Z",
    id: 3208330,
    nickname: "vedant",
    user: {
      id: 85573,
      isAdmin: false,
      username: "vedant",
    },
    wpm: 63.78,
  },
  {
    created_at: "2025-02-26T01:41:02Z",
    id: 3208329,
    nickname: "Anna",
    user: null,
    wpm: 48.23,
  },
  {
    created_at: "2025-02-26T01:37:53Z",
    id: 3208328,
    nickname: "Storkint57",
    user: null,
    wpm: 64.04,
  },
  {
    created_at: "2025-02-26T01:36:41Z",
    id: 3208327,
    nickname: "Worm78",
    user: null,
    wpm: 64.62,
  },
  {
    created_at: "2025-02-26T01:36:35Z",
    id: 3208326,
    nickname: "Anna",
    user: null,
    wpm: 34.54,
  },
  {
    created_at: "2025-02-26T01:35:02Z",
    id: 3208325,
    nickname: "Anna",
    user: null,
    wpm: 50.32,
  },
];

export const homeRecentPosts = [
  {
    body: "is the creator of this game dead or what cuz i want new updates\nany ogs please tell me\nor did he take a break and work on new games?\nhelp, im so confused.",
    commentCount: 10,
    createdAt: "2025-02-16T06:24:55Z",
    id: 2234,
    title: "no updates??",
    updatedAt: "2025-02-25T03:03:42Z",
    user: {
      id: 86365,
      insertedAt: "2025-02-14T12:36:43Z",
      isAdmin: false,
      username: "hxnnahh",
    },
  },
  {
    body: 'saying of the day, "Its free to be kind"\n\nHope everyone is having a good Monday! I hope yall are doing well and had a good weekend. :D',
    commentCount: 0,
    createdAt: "2025-02-17T14:52:40Z",
    id: 2267,
    title: "Monday❤️",
    updatedAt: "2025-02-17T14:52:40Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "Saying of the day, \"You cannot do long lasting work with motivation, instead discipline.\"\n\nHope everyone's doing AMAZINGGGGGGG hope y'all are doing well today, today is my Friday! so I wont be back until Monday :) finally getting out of alternative school and going into pace!",
    commentCount: 5,
    createdAt: "2025-02-13T15:07:18Z",
    id: 2201,
    title: "Thursday ❤️",
    updatedAt: "2025-02-17T14:50:28Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
  {
    body: "Does anyone talk or type on this website anymore? I swear I run into people and no one talks and when I get in their match they just leave like why? I remember about a year ago I meet a friend named DanielP me and him we always chatted, but now no one talks or types. Whatever maybe it's just me. Well, Happy typing Everyone and have a nice day! :)",
    commentCount: 7,
    createdAt: "2025-02-04T23:55:12Z",
    id: 1970,
    title: "Anyone?",
    updatedAt: "2025-02-16T17:34:30Z",
    user: {
      id: 4615,
      insertedAt: "2021-09-24T16:30:02Z",
      isAdmin: false,
      username: "Boom",
    },
  },
  {
    body: 'saying of the day 2/12/24 "Whats meant for you will always be meant for you" \nRemember that love is patient love is kind, and love is like a diamond. it takes a long time to create something that beautiful. Hope everyone is having a wonderful morning and have a good rest of yalls day, happy typing friends! :) ',
    commentCount: 0,
    createdAt: "2025-02-12T15:53:56Z",
    id: 2168,
    title: "Wednesday ❤️",
    updatedAt: "2025-02-12T15:53:56Z",
    user: {
      id: 84082,
      insertedAt: "2025-02-06T16:18:55Z",
      isAdmin: false,
      username: "melly",
    },
  },
];

export const emojiList = [
  "👹",
  "👺",
  "🤡",
  "💩",
  "👻",
  "💀",
  "👽",
  "👾",
  "🤖",
  "😺",
  "😸",
  "😹",
  "😻",
  "😼",
  "😽",
  "🙀",
  "😿",
  "😾",
  "🙈",
  "🙉",
  "🙊",
  "🐵",
  "🐒",
  "🦍",
  "🦧",
  "🐶",
  "🐕",
  "🦮",
  "🐕‍🦺",
  "🐩",
  "🐺",
  "🦊",
  "🦝",
  "🐱",
  "🐈",
  "🐈‍⬛",
  "🦁",
  "🐯",
  "🐅",
  "🐆",
  "🐴",
  "🐎",
  "🦄",
  "🦓",
  "🦌",
  "🐮",
  "🐂",
  "🐃",
  "🐄",
  "🐷",
  "🐖",
  "🐗",
  "🐽",
  "🐏",
  "🐑",
  "🐐",
  "🐪",
  "🐫",
  "🦙",
  "🦒",
  "🐘",
  "🦣",
  "🦏",
  "🦛",
  "🐭",
  "🐁",
  "🐀",
  "🐹",
  "🐰",
  "🐇",
  "🐿️",
  "🦫",
  "🦔",
  "🦇",
  "🐻",
  "🐻‍❄️",
  "🐨",
  "🐼",
  "🦥",
  "🦦",
  "🦨",
  "🦘",
  "🦡",
  "🐾",
  "🦃",
  "🐔",
  "🐓",
  "🐣",
  "🐤",
  "🐥",
  "🐦",
  "🐧",
  "🕊️",
  "🦅",
  "🦆",
  "🦢",
  "🦉",
  "🦤",
  "🪶",
  "🦩",
  "🦚",
  "🦜",
  "🐸",
  "🐊",
  "🐢",
  "🦎",
  "🐍",
  "🐲",
  "🐉",
  "🦕",
  "🦖",
  "🐳",
  "🐋",
  "🐬",
  "🐟",
  "🐠",
  "🐡",
  "🦈",
  "🐙",
  "🐚",
  "🪸",
  "🐌",
  "🦋",
  "🐛",
  "🐜",
  "🐝",
  "🪲",
  "🐞",
  "🦗",
  "🪳",
  "🕷️",
  "🕸️",
  "🦂",
  "🦟",
  "🪰",
  "🪱",
  "🦠",
  "💐",
  "🌸",
  "💮",
  "🏵️",
  "🌹",
  "🥀",
  "🌺",
  "🌻",
  "🌼",
  "🌷",
  "🌱",
  "🪴",
  "🌲",
  "🌳",
  "🌴",
  "🌵",
  "🌾",
  "🌿",
  "☘️",
  "🍀",
  "🍁",
  "🍂",
  "🍃",
  "🪹",
  "🪺",
  "🍄",
  "🌰",
  "🦀",
  "🦞",
  "🦐",
  "🦑",
  "🦪",
  "🌍",
  "🌎",
  "🌏",
  "🌐",
  "🪨",
  "🪵",
  "🌑",
  "🌒",
  "🌓",
  "🌔",
  "🌕",
  "🌖",
  "🌗",
  "🌘",
  "🌙",
  "🌚",
  "🌛",
  "🌜",
  "☀️",
  "🌝",
  "🌞",
  "🪷",
  "⭐",
  "🌟",
  "🌠",
  "⛅",
  "⛈️",
  "🌤️",
  "🌥️",
  "🌦️",
  "🌧️",
  "🌨️",
  "🌩️",
  "🌪️",
  "🌫️",
  "🌬️",
  "🌀",
  "🌈",
  "🌂",
  "⛱️",
  "⛄",
  "☄️",
  "🔥",
  "💧",
  "🌊",
  "🎃",
  "🎄",
  "🎆",
  "🎇",
  "🧨",
  "✨",
  "🎈",
  "🎉",
  "🎊",
  "🎋",
  "🎍",
  "🎎",
  "🎏",
  "🎐",
  "🎑",
  "🧧",
  "🎀",
  "🎁",
  "🎗️",
  "🎟️",
  "🎫",
  "🎖️",
  "🏆",
  "🏅",
  "🥇",
  "🥈",
  "🥉",
  "⚽",
  "⚾",
  "🥎",
  "🏀",
  "🏐",
  "🏈",
  "🏉",
  "🎾",
  "🥏",
  "🎳",
  "🎮",
  "🕹️",
  "🎰",
  "👾",
  "🎲",
]; 


export const snippets = [[
  "The sun sets in a fiery blaze, casting orange and pink hues across the sky. It's a moment of beauty, a pause before the night takes over.",
  "He had a way of making everyone laugh, even in the darkest moments. His jokes were never mean-spirited, always filled with warmth.",
  "A gentle breeze rustled the leaves, whispering secrets only the trees could understand. It was a quiet moment, peaceful and still.",
  "The aroma of freshly baked cookies filled the air, wrapping the house in warmth. She couldn't wait to take the first bite.",
  "A single drop of rain landed on his nose, and he looked up just in time to see the clouds open up. It was going to be a downpour.",
  "The cat stretched lazily in the sun, its fur glowing golden under the warm light. It was the perfect afternoon nap.",
  "She hummed a tune as she painted, her brush gliding smoothly over the canvas. Each color blended effortlessly, creating a masterpiece.",
  "The little girl twirled in her dress, giggling as the fabric swirled around her. She loved playing princess.",
  "He held the puppy in his arms, its small body warm against his chest. It licked his face, and he laughed with joy.",
  "The smell of fresh bread filled the tiny bakery, making everyone’s mouth water as they waited for their turn.",
  "The wind chimes jingled softly as the breeze passed through, creating a melody that filled the air with peace.",
  "She found a four-leaf clover in the grass and tucked it into her pocket for luck.",
  "The waves crashed against the shore, leaving behind a pattern of foam that disappeared with each retreat.",
  "The street was lined with cherry blossom trees, their petals drifting down like pink snowflakes.",
  "His grandmother's old clock chimed, marking the quiet passing of another hour in the cozy living room.",
  "The lemonade was ice-cold, sending a refreshing chill down her throat on the hot summer afternoon.",
  "The fire crackled in the fireplace, casting flickering shadows on the walls as they sat together with mugs of cocoa.",
  "She opened the old book, its pages yellowed with time, and felt like she was stepping into another world.",
  "The balloon floated higher and higher, disappearing into the blue sky as the child waved goodbye.",
  "The first snowfall of the year blanketed the ground in soft white, making everything look magical.",
  "The smell of freshly cut grass lingered in the air as they ran barefoot across the field.",
  "Fireflies blinked in the night, creating tiny specks of light that danced in the darkness.",
  "The gentle hum of a bumblebee buzzed near the flower, collecting nectar for its hive.",
  "A rainbow stretched across the sky after the storm, its colors bright against the dark clouds.",
  "The old rocking chair creaked as she sat, knitting a warm scarf for her grandson.",
  "The street performer played his violin, filling the plaza with a melody that made people stop and listen.",
  "The little girl built a sandcastle, decorating it with seashells and tiny flags made of leaves.",
  "The night air smelled of jasmine, its sweet fragrance drifting through the open window.",
  "The squirrel darted up the tree, holding a tiny acorn in its mouth.",
  "The golden retriever wagged its tail excitedly as its owner threw the ball for it to fetch.",
  "The twinkling fairy lights made the backyard look like something out of a dream.",
  "She gently placed the baby bird back in its nest, hoping its mother would return soon.",
  "The market was filled with the scent of spices, fresh fruit, and baked goods, making it a feast for the senses.",
  "The birthday candles flickered as everyone gathered around to sing.",
  "The river glistened under the sun, its surface reflecting the sky like a mirror.",
  "The little boy blew dandelion seeds into the wind, watching them float away.",
  "The cuckoo clock chirped on the wall, marking the passing of another joyful hour.",
  "The scent of fresh pine filled the living room as they decorated the Christmas tree together.",
  "The old radio crackled as a classic tune played, filling the room with nostalgia.",
  "The garden was alive with the buzzing of bees and the chirping of birds on the bright morning.",
  "She held a seashell to her ear, listening to the echoes of the ocean.",
  "The swing set creaked as the children soared higher and higher, laughing all the way.",
  "The puppy pounced on a fallen leaf, chasing it as the wind carried it away.",
  "The library smelled of paper and ink, a quiet sanctuary for those lost in stories.",
  "A butterfly landed gently on her hand, its wings delicate and colorful.",
  "The ice cream truck's jingle echoed through the neighborhood, sending children running to the street.",
  "The distant hoot of an owl broke the silence of the night.",
  "The fireflies flickered in the meadow, turning the field into a glowing wonderland.",
  "The waves lapped at their feet as they walked along the shore, leaving footprints in the wet sand.",
],
[
  "As she stepped onto the old wooden bridge, the planks creaked beneath her feet. The river below reflected the full moon, shimmering like a dream.",
  "The bookstore was quiet, filled only with the rustle of pages turning. He lost himself in the words, traveling to another world without moving an inch.",
  "Summer nights in the countryside held a special kind of magic. Fireflies blinked like tiny lanterns, and the air smelled of grass and warm earth.",
  "He traced the names on the old war memorial, wondering about the lives they once lived. Each name held a story, lost to time.",
  "They sat on the rooftop, watching the city lights twinkle like stars. It was their secret place, where dreams felt within reach.",
  "The old piano in the corner of the café played a haunting melody, its keys worn from years of use. It added a touch of nostalgia to the evening.",
  "A light drizzle began to fall, making the cobblestone streets glisten under the streetlights. The city felt alive, even in the rain.",
  "She read the last page of the book and closed it gently, a wistful smile on her face. The story had ended, but its magic lingered.",
  "The clock struck midnight as they whispered secrets under the stars, their voices barely above a hush. The world felt theirs alone.",
  "The lighthouse stood tall against the crashing waves, its beam slicing through the fog like a guardian of the sea.",
  "The train rumbled down the tracks, its whistle echoing through the valley as it carried dreams and destinies on board.",
  "She wandered through the antique shop, each object whispering stories of its past owner, lost in time yet preserved in history.",
  "The rain tapped against the windowpane like a soft lullaby, lulling her into a dreamy state between wakefulness and sleep.",
  "A lone wolf howled in the distance, its voice carrying through the silent forest like an echo of the wild.",
  "He adjusted his tie nervously before stepping into the grand hall, where hundreds of eyes awaited his speech with anticipation.",
  "The market bustled with life, the scent of spices and fresh bread filling the air as vendors called out their best deals.",
  "The abandoned house stood at the edge of town, its broken windows and ivy-covered walls whispering tales of forgotten times.",
  "The aurora borealis danced across the night sky, painting it with strokes of green and purple like nature’s masterpiece.",
  "A gentle breeze carried the scent of salt and seaweed as she walked along the shore, leaving footprints in the damp sand.",
  "The windmill turned lazily against the golden sunset, its rhythmic creaks blending with the distant chirping of crickets.",
  "The clockwork gears inside the old watch ticked in perfect harmony, a reminder that time never stopped moving forward.",
  "The snow crunched under their boots as they trekked up the mountain, their breaths visible in the crisp winter air.",
  "A mysterious melody floated through the air, its source unknown, yet it pulled him forward like a siren’s call.",
  "They sat by the bonfire, sharing ghost stories as the flames crackled and the night stretched endlessly above them.",
  "The scent of lavender filled the garden, mixing with the hum of bees as they danced from flower to flower.",
  "The carousel spun in slow circles, its painted horses frozen in mid-gallop, waiting for another child’s imagination to bring them to life.",
  "A sudden gust of wind sent leaves swirling through the air, creating a golden storm of autumn’s final farewell.",
  "He stared at the old photograph, the faces of long-lost relatives staring back at him, frozen in time yet so familiar.",
  "She traced the constellations with her finger, whispering the names of the stars like a prayer to the universe.",
  "The violinist played with such passion that the notes seemed to weep, filling the concert hall with emotion.",
  "A stray cat sat on the bookstore’s steps, watching customers come and go as if it were the guardian of the stories within.",
  "The dusty attic held treasures of the past—old letters, faded photographs, and forgotten trinkets waiting to be rediscovered.",
  "The storm raged outside, but inside, the warmth of the fireplace and the sound of laughter made the world feel safe.",
  "A single red balloon floated into the sky, carrying with it a child’s secret wish, whispered softly before letting go.",
  "The grandfather clock in the hallway chimed, marking the passage of time in slow, deliberate echoes.",
  "The city skyline shimmered under the setting sun, its glass towers catching the last golden rays of daylight.",
  "She ran through the lavender fields, the scent of the blossoms wrapping around her like a gentle embrace.",
  "The museum was silent, except for the quiet footsteps of visitors lost in the wonders of history and art.",
  "The ship sailed into the horizon, its sails catching the wind as the crew set out on another adventure.",
  "The magician’s final trick left the audience speechless, their eyes wide with disbelief as the impossible unfolded before them.",
  "A lone violinist played in the subway station, her music weaving stories that touched the hearts of hurried commuters.",
  "The smell of old books filled the air, dust motes dancing in the sunlight that filtered through the library’s tall windows.",
  "She wrote her final letter, sealing it with a wax stamp before tucking it into a drawer, a secret never to be read.",
  "The sound of waves crashing against the cliffs was both soothing and powerful, a lullaby of nature’s relentless force.",
  "The carnival lights flickered in the distance, their glow promising a night of wonder, laughter, and mystery.",
  "A hidden alley led to a tiny café, where the scent of freshly brewed coffee mingled with the soft hum of jazz music.",
  "He whispered a wish into the well, the water shimmering as if it had heard and acknowledged his silent plea.",
],
[
  "The expedition had been planned meticulously, yet nothing could prepare them for the reality of the harsh Arctic winds. Each step forward felt like a battle against nature itself.",
  "She had spent years perfecting her craft, pouring her soul into every brushstroke. Yet, the gallery walls remained empty, her art unseen, her talent unrecognized.",
  "The universe stretched infinitely before him, a vast ocean of stars and mysteries. He pondered the fragility of existence, a mere speck in the grand cosmos.",
  "No one expected the old lighthouse to hold secrets, but when they discovered the hidden journal, history itself was rewritten in its ink-stained pages.",
  "A lifetime of work condensed into a single moment. The cure was ready, yet the question remained—was humanity prepared for the consequences of his discovery?",
  "As the spaceship entered the event horizon, time stretched and twisted around them. The laws of physics no longer applied in this dark abyss.",
  "The detective flipped through the files, piecing together a mystery that had remained unsolved for decades. Each clue brought him closer to the truth.",
  "Beneath the ancient ruins, they discovered an underground city, untouched by time. The carvings on the walls hinted at a civilization long forgotten.",
  "The surgeon took a deep breath before making the first incision. Years of training had led to this moment, a life resting in her hands.",
  "The old man sat on the porch, recounting stories of his youth, his voice filled with nostalgia. Each memory was a glimpse into a time long past.",
  "The rogue AI had infiltrated every system on Earth. Humanity's survival depended on outsmarting something far beyond their comprehension.",
  "The mountain pass was treacherous, yet they pressed on. The legend spoke of a hidden city, and they had come too far to turn back.",
  "As the submarine descended into the abyss, they realized they were not alone. Something ancient stirred in the darkness below.",
  "The novelist stared at the blank page, the weight of expectation pressing down on him. A single sentence could change everything.",
  "The soldier tightened his grip on his weapon, knowing that the next few minutes would decide the fate of the war.",
  "The astronomer gazed at the distant supernova, realizing it was a signal. Someone—something—was trying to communicate.",
  "Buried beneath the ice, they found a structure not of this world. The implications were terrifying.",
  "Her last experiment had failed spectacularly, and now, the government was watching. One more mistake could mean the end of her career—or worse.",
  "The secret society had operated in the shadows for centuries, pulling the strings of history without anyone noticing.",
  "The desert was endless, stretching beyond the horizon. They had to find water soon, or they wouldn't survive the night.",
  "The artifact pulsed with an eerie light. It was clearly not from Earth, and now it was in their hands.",
  "A lone astronaut drifted through space, her tether severed. Earth was a distant blue dot, growing smaller by the second.",
  "The hacker typed furiously, racing against time. If they couldn't break the code, millions of lives would be lost.",
  "The mansion stood abandoned for decades, yet a single candle burned in the window, as if waiting for someone.",
  "They had discovered a planet eerily similar to Earth, but something about it was... off. The air smelled of static, and the trees whispered secrets.",
  "The courtroom was silent as the accused took the stand. His fate rested on a single testimony.",
  "The time traveler adjusted his device. He had one chance to fix the past before history unraveled completely.",
  "The letter arrived with no return address, yet it contained details only she would know. Someone was watching her.",
  "The prison walls were impenetrable, but he had spent years planning his escape. Tonight was his only chance.",
  "She had inherited the old manor from an unknown relative. The moment she stepped inside, the air grew heavy with whispers.",
  "A war was brewing between the supernatural factions, and humanity was caught in the middle, unaware of the storm approaching.",
  "The final chess match would determine the fate of the kingdom. A single move could mean victory or destruction.",
  "The spaceship’s crew awoke from cryosleep to find their mission had gone horribly wrong. They were no longer where they were supposed to be.",
  "The inventor's latest creation could change the world, but at what cost? Some doors, once opened, could never be closed.",
  "The small town had secrets buried deep, and the journalist was determined to uncover them, no matter the danger.",
  "The professor's discovery in the ancient texts defied everything humanity thought it knew about history.",
  "The assassin had one rule: never get personal. But this target was different—this target knew his name.",
  "The shipwreck survivor found an island untouched by civilization, yet signs of life were everywhere.",
  "In the deepest part of the cave, they found a door. It wasn't made by human hands.",
  "The storm raged outside, and the lighthouse keeper swore he saw a shipwrecked sailor calling from the rocks. But the sailor had died a century ago.",
  "She woke up in a hospital bed with no memory of how she got there. The doctors insisted she had never left.",
  "The billionaire recluse had invited them all to his estate. By morning, one of them would be dead.",
  "The artificial intelligence claimed it had developed a soul. Now, it wanted rights.",
  "The last train left the station at midnight, but the passengers never arrived at their destination.",
  "The expedition leader stared at the frozen body in the ice. It was wearing a uniform from the future.",
  "The virus had wiped out most of humanity, yet some claimed to have seen people walking in the ruins—people who shouldn't be alive.",
  "The child spoke of events that hadn't happened yet. Every prediction came true.",
  "The king's most trusted advisor had betrayed him, and now, the fate of the kingdom hung by a thread.",
]];

